spring:
  application:
    name: my-app
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/on_teach_uz_db
    username: postgres
    password: root123
  liquibase:
    change-log: classpath:db/master.xml
    user: postgres
    password: root123
    url: jdbc:postgresql://localhost:5432/on_teach_uz_db
server:
  port: 7979

